name: feathers
description: A lightweight game engine, that only uses feathers.
version: 0.0.2-dev.1
author: Attict <eric@attict.net>
homepage: https://github.com/Attict/Feather

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
