name: feathers
description: Lightweight flexible app & game engine where you get to feather your application the way you want it, using a node based approach with components that can be customized.
version: 0.0.1-beta.5
author: Attict <eric@attict.net>
homepage: https://github.com/Attict/Feather

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
